### ISSUE TITLE
Can't find fix_ios.js and run.js

### ISSUE THREAD

**Issue by zepspaiva** [Toumassa/jitsi-meet-cordova-ios#1]
Hi!
Congrats for the project and for getting this working. I'm trying to make it work with my server, but I think I'm missing something.

I already had an working version of jitsi-meet on my server. Tried to use this project to create an app for iOS that could connect to my server but it seems that the fix_ios.js and run.js files are missing. When I put the provided index.html on my server it cannot inject the default index (that was renamed).

Can you, please help me?
Thanks,

**Comment by Toumassa** [comment]
I've added these file, please pull and keep me informed

**Comment by zepspaiva** [comment]
Thank you!!
