### ISSUE TITLE
which version of jitsi is required?

### ISSUE THREAD

**Issue by roeycohen** [Toumassa/jitsi-meet-cordova-ios#2]
hi,
does this code works? does someone knows if it works on the most recent version of jitsi?
10x

**Comment by Toumassa** [comment]
This code works, but not with the latest code. It works with my own fork of lib-jitsi-meet and the version of jitsi-meet associated with that (3 Jun 2016 too old now...). 
BTW there is the solution with reactive native for mobile devices (see jitsi-meet project) developed and maintained by jitsi team. 
So i will not maintain this project.

**Comment by roeycohen** [comment]
hi @Toumassa,

1st, thanks for replying.

too bad you won't continue with this fork as it's not giving the same solution as jitsi's react native project.
their project won't allow mixing html elements while this project does.

**Comment by Toumassa** [comment]
Thank you for your interest,

Me too I think the idea of having the same code for both, mobile & web is elegant. However it requires too much time. In addition, the web UI of jitsi-meet is not optimized for mobiles, at all (performance, ergonomy)... So, in my opinion, it's better to start an UI from scratch using cordova(or react-native) using jitsi's Videobridge (the SFU) which is the argument of Jitsi suite.
Having said that, this solution had as objective to bring a solution for iOS's lack of webrtc support. In long term, iOS will support WebRTC, which is partially achieved using cordova-plugin-iosrtc or react-native.

**Comment by roeycohen** [comment]
hi @Toumassa 

i already have a custom UI working on Android, do you think https://github.com/Toumassa/lib-jitsi-meet should work with more recent version of jitsi's server?

10x again

**Comment by Toumassa** [comment]
Hi,

I don't think it will work. They have rewritten the whole code since that version. 
But if you want you can easily add your UI app as new kind of browser (user agent and other differences) in module/RTC section. As example you have 'React Native App' in their code.
Not very hard.

The last tested version seem to be the commit bbc91f6e0ccf02156899bd1f1501daad0479417a (19 apr 2016)

**Comment by roeycohen** [comment]
Hi 

thank you so much for your tips, but my base knowledge in this project is low...
could you give me a few more hints about what is "module/RTC" or how can i use a webview as a new App?

🙏

**Comment by roeycohen** [comment]
i'm thinking about rewriting your changes to the most recent version of lib-jitsi-meet.
any ideas why shouldn't i?

**Comment by roeycohen** [comment]
it's weird, but it seems that making lib-jitsi-meet "think" that you're running inside chrome should work, but it's not...

**Comment by Toumassa** [comment]
Hi, i'm not up to date about the changes that they introduced. However i dont think that it is complicated to rewrite my changes for the latest stable version. 

What differs from browser to browser are mostly in folder modules/RTC. 

AFAIK they already distingish different browsers, chrome, firefox,..., react ios. First start by adding a new browser type , and start by implementing what is specific: user agent, webrtc api variables exposed by the iosrtc plugin ....

What was difficult for me is exposing webrtc variables correctly before throwing RTC ready event.

**Comment by Toumassa** [comment]
You can search for ´isiOSRTC´ which should bring all specific implementations that i've introduced to my ´browser'.

**Comment by roeycohen** [comment]
i'm glad to say that i was able to make lib-jitsi-meet work :)
it was pretty easy at the end...
i've modified the chrome detect function to work also for ios and fixed a minor race condition.
also needed to make a small change to the stream.id in the IOSRTC plugin.
i'm still testing it, but i think my find should be merged to the lib-jitsi-meet master.
